images:
  gitea: .
  gitea-logo: ../gitea-logo
  gitea-custom: ../gitea-custom
  gitea-disable: ../gitea-disable
  certbot-latest: ../certbot

volumes:
  gitea-data:
    chmod: 0750
    chown: 211:211
    zfs:
      quota: 5G
  certbot-webroot: {}
  certbot-config-gitea: {}

jails:
  gitea:
    meta:
      domains:
        - xyz.com
        - www.xyz.com
    image: gitea-disable
    mounts:
      gitea-data: /var/db/gitea
    ip4.addr: 127.0.8.1
    exec.start: |
      export IP4_ADDR=127.0.8.1 && \
      export SCHEME=http && \
      export DOMAIN_NAME=localhost:3001 && \
      export GITEA_CONF=/usr/local/etc/gitea/conf/app.ini && \
      chown git:git /var/db/gitea && \
      sed -i -e "s/127.0.0.1/${IP4_ADDR}/g" $GITEA_CONF && \
      sed -i -e "s/localhost/${DOMAIN_NAME}/g" $GITEA_CONF && \
      crudini --set --inplace $GITEA_CONF server ROOT_URL ${SCHEME}://${DOMAIN_NAME} && \
      if [ ! -f /var/db/gitea/gitea.db ]; then \
        su git -c 'gitea migrate -c $GITEA_CONF' && \
        su git -c 'gitea admin -c $GITEA_CONF create-user --username admin1 --password "AdminAdmin1+" --email "invaliduser@nonexistentdomain.com" --admin'; \
      fi && \
      /bin/sh /etc/rc

  certbot-gitea:
    image: certbot-latest
    mounts:
      certbot-webroot: /certbot/webroot
      certbot-config-gitea: /usr/local/etc/letsencrypt
    ip4.addr: 127.0.9.1
    exec.start: |
      if [ ! -f /usr/local/etc/letsencrypt/cli.ini ]; then
        echo 'webroot-path=/certbot/webroot' >>/usr/local/etc/letsencrypt/cli.ini && \
        echo 'authenticator=webroot' >>/usr/local/etc/letsencrypt/cli.ini;
      fi && \
      /bin/sh /etc/rc
