exec.prebuild:
  - python3 getmetadata.py


volumes:
  certbot-data:
    chown: 65534:65534
    chmod: 0750
    zfs:
      quota: 1G
  certbot-webroot:
    chown: 65534:65534
    chmod: 0750
    zfs:
      quota: 1G


images:
  nginx-http: ./nginx-http
  nginx-https: ./nginx-https
  certbot: ./certbot


jails:
  nginx-http:
    image: nginx-http
    mounts:
      certbot-webroot: /certbot/webroot
    ip4.addr: 127.0.12.1

  certbot:
    image: certbot
    depend: nginx-http
    mounts:
      certbot-data: /usr/local/etc/letsencrypt
      certbot-webroot: /certbot/webroot
    exec.start: |
      if [ ! -f /certbot/data/.ready ]; then
        rm -vf /usr/local/etc/letsencrypt/.ready && \
        /usr/local/bin/python3 /certbot/scripts/certbot.py && \
        touch /usr/local/etc/letsencrypt/.ready && \
        touch /certbot/data/.ready;
      fi && \
      /bin/sh /etc/rc
    ip4.addr: 127.0.13.1

  nginx-https:
    image: nginx-https
    depend:
      - certbot
      - nginx-http
    mounts:
      certbot-data: /usr/local/etc/letsencrypt
    exec.start: |
      ( until [ -f /usr/local/etc/letsencrypt/.ready ]; do sleep 1; done && \
      /bin/sh /etc/rc) &
    ip4.addr: 127.0.14.1
