prebuild:
  - python3 getmetadata.py


volumes:
  certbot-data:
    chown: 65534:65534
    chmod: 0750
    zfs:
      quota: 1G
  certbot-webroot:
    chown: 65534:65534
    chmod: 0750
    zfs:
      quota: 1G


images:
  nginx-http: ./nginx-http
  nginx-https: ./nginx-https
  certbot: ./certbot


jails:
  nginx-http:
    image: nginx-http
    mounts:
      certbot-webroot: /certbot/webroot

  certbot:
    image: certbot
    depend: nginx-http
    mounts:
      certbot-data: /usr/local/etc/letsencrypt
      certbot-webroot: /certbot/webroot
    exec.start: |
      ( /usr/bin/su -m nobody -c "python3 /certbot/scripts/certbot.py" && \
      /bin/sh /etc/rc ) &

  nginx-https:
    image: nginx-https
    depend: certbot
    mounts:
      certbot-data: /usr/local/etc/letsencrypt
